# .github/workflows/firebase-deploy.yml
name: 🚀 Deploy to Firebase Hosting

on:
  push:
    branches:
      - dev    # adjust to your release branch (e.g. main) as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken:                 ${{ secrets.GITHUB_TOKEN }}                   # for GitHub status checks
          firebaseServiceAccount:    ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}   # your raw JSON service-account key
          projectId:                 sadaf-dev                                   # your Firebase project ID
          channelId:                 live                                           # “live” = production channel
